version: "3"
services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: superPassword
      POSTGRES_DB: database
