version: "3.7"
services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    links:
      - "postgres:database"
    environment:
      DATABASE_URL: postgres://superUser:superPassword@database/super-database
      AUTH_SECRET: superSecret
  postgres:
    container_name: pg
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: superPassword
      POSTGRES_DB: super-database
