org: kolyamba2105
app: sls-fp-pg-api
service:
  name: fp-pg-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_PATH: ${param:NODE_PATH}
    ENV: ${param:ENV}
    DATABASE_NAME: ${param:DATABASE_NAME}
    DATABASE_HOST: ${param:DATABASE_HOST}
    DATABASE_USERNAME: ${param:DATABASE_USERNAME}
    DATABASE_PASSWORD: ${param:DATABASE_PASSWORD}
    AUTH_SECRET: ${param:AUTH_SECRET}
    
functions:
  app:
    handler: src/app.sls
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
